name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        #!/bin/bash
        b=''
        i=0
        while [ $i -le  100 ]
        do
            printf "progress:[%-50s]%d%%\r" $b $i
            sleep 1
            i=`expr 2 + $i`       
            b=#$b
        done
        echo
